{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
{{- range $name, $svc := .Values.services }}
          - path: {{ $svc.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-{{ $name }}
                port:
                  number: {{ $svc.port }}
{{- end }}
{{- end }}

